app = 'portfolio-frosty-glade-30'
primary_region = 'fra'

[build]
  dockerfile = 'Dockerfile'

[[services]]
  internal_port = 3000        # порт, на котором слушает Express
  protocol      = 'tcp'

  [[services.ports]]
    port     = 80             # внешний порт Fly
    handlers = ['http']       # указываем, что это HTTP‑трафик

[[vm]]
  memory   = '1gb'
  cpu_kind = 'shared'
  cpus     = 1
