services:
  db:
    image: mongo:6 
    ports:
      - "27017:27017"
    environment:
      MONGODB_BIND_IP: "0.0.0.0" 
      
    command: ["mongod", "--replSet", "rs0"] 
    volumes:
      - mongo-data:/data/db #
      - ./init-replica.js:/docker-entrypoint-initdb.d/init-replica.js:ro
    restart: unless-stopped 
  express-app: 
    build: . 
    ports:
      - "3000:3000" 
    depends_on:
      - db 
    environment:
      DATABASE_URL: "mongodb://db:27017/mydatabase?replicaSet=rs0&directConnection=true" 
      SECRET_KEY: "123" 
      NODE_ENV: development 
    volumes:
      - .:/app
      - /app/node_modules
    restart: unless-stopped 

  react-app: 
    build: ../portfolio-social-client
    ports:
      - "80:80"
    # volumes:
    #   - ../portfolio-social-client:/app
    #   - /app/node_modules
    restart: unless-stopped
    depends_on:
      - express-app

volumes:
  mongo-data: 