services:
  db:
    image: mongo:6 
    ports:
      - "27017:27017"
    environment:
      MONGODB_BIND_IP: "0.0.0.0" 
    command: ["sh", "-c", "mongod --replSet rs0 --bind_ip_all & sleep 10 && mongo --eval 'rs.initiate({ _id: \"rs0\", members: [{ _id: 0, host: \"db:27017\" }] })'"]
    volumes:
      - mongo-data:/data/db
      - ./init-replica.js:/docker-entrypoint-initdb.d/init-replica.js:ro
    restart: unless-stopped 
  express-app: 
    build: . 
    ports:
      - "3000:3000" 
    depends_on:
      - db 
    env_file:
      - ./.env
    # environment:
    #   DATABASE_URL: "mongodb://db:27017/mydatabase?replicaSet=rs0&directConnection=true" 
    #   SECRET_KEY: "123" 
    #   NODE_ENV: development 
    volumes:
      - .:/app
      - /app/node_modules
    restart: unless-stopped 

  react-app: 
    build: 
      context: ../portfolio-social-client
      args:
        - VITE_BASE_URL=http://16.16.25.78:3000
        - NODE_OPTIONS=--max-old-space-size=4096
    ports:
      - "80:80"
    restart: unless-stopped
    depends_on:
      - express-app

volumes:
  mongo-data:
